# Generated by Django 3.1.2 on 2020-11-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vvouch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40, verbose_name='activation')),
                ('activation_key', models.CharField(max_length=40, verbose_name='activation key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
        ),
    ]
