# Generated by Django 3.1.2 on 2021-03-15 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vvouch', '0003_auto_20210220_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=100)),
                ('product_type', models.CharField(blank=True, max_length=100)),
                ('product_quantity', models.CharField(blank=True, max_length=100)),
                ('product_reviews', models.CharField(blank=True, max_length=100)),
                ('product_website', models.CharField(blank=True, max_length=100)),
                ('product_relevant_page', models.CharField(blank=True, max_length=100)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('seller_email', models.CharField(blank=True, max_length=100)),
                ('product_status', models.CharField(default='0', max_length=100)),
            ],
        ),
    ]
