# Generated by Django 3.1.2 on 2021-03-15 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vvouch', '0004_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='seller_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
