# Generated by Django 3.1.2 on 2021-03-15 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vvouch', '0005_auto_20210315_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='seller_id',
            new_name='seller',
        ),
    ]
