# Generated by Django 3.1.2 on 2021-03-15 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import vvouch.models


class Migration(migrations.Migration):

    dependencies = [
        ('vvouch', '0006_auto_20210315_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=255, upload_to=vvouch.models.ticket_file_path)),
                ('is_deleted', models.BooleanField(blank=True, default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_added_by', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_id', to='vvouch.products')),
            ],
        ),
    ]
