# Generated by Django 3.1.2 on 2021-03-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vvouch', '0007_productimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='file',
            field=models.FileField(blank=True, max_length=255, upload_to=''),
        ),
    ]
