# Generated by Django 3.1.2 on 2021-04-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vvouch', '0008_auto_20210315_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='file',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
